_wandb:
    value:
        cli_version: 0.19.8
        m:
            - "1": train_acc
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": epoch
              "6":
                - 3
              "7": []
            - "1": train_loss
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": val_acc
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": val_loss
              "5": 2
              "6":
                - 1
                - 3
              "7": []
        python_version: 3.10.16
        t:
            "1":
                - 1
                - 41
                - 49
                - 55
                - 63
            "2":
                - 1
                - 41
                - 49
                - 55
                - 63
            "3":
                - 7
                - 13
                - 16
                - 23
                - 55
                - 62
            "4": 3.10.16
            "5": 0.19.8
            "8":
                - 5
            "12": 0.19.8
            "13": linux-x86_64
batch_size:
    value: 256
dataset:
    value: cifar10
epochs:
    value: 50
image_size:
    value: 70
learning_rate:
    value: 0.0003
optimizer:
    value: adamw
optimizer_betas:
    value:
        - 0.9
        - 0.999
optimizer_momentum:
    value: 0.9
